language: php

php:
  - 7.2

services:
  - mysql

before_install:
  - mysql -e 'create database ecquotes;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - vendor/bin/phpunit

notifications:
    email: false
