// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// feedback.js
export const RESPONSE_MSG = 'RESPONSE_MSG'
export const CLEAR_MSG = 'CLEAR_MSG'

// company.js
export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_FAILURE = 'FETCH_COMPANIES_FAILURE'

// dialog.js
export const UPDATE_ADD_ITEM_DIALOG_STATUS = 'UPDATE_ADD_ITEM_DIALOG_STATUS'
export const UPDATE_COPY_ITEM_DIALOG_STATUS = 'UPDATE_COPY_ITEM_DIALOG_STATUS'

// prouducts.js
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCTS_LINE = 'FETCH_PRODUCTS_LINE'

// order.js
export const SAVE_ORDER = 'SAVE_ORDER'
export const SAVE_ORDER_PO_REFERENCE = 'SAVE_ORDER_PO_REFERENCE'
export const SAVE_ORDER_CUSTOMER_NAME = 'SAVE_ORDER_CUSTOMER_NAME'
export const SAVE_ORDER_COMPANY_ID = 'SAVE_ORDER_COMPANY_ID'
export const SAVE_ORDER_PRODUCT = 'SAVE_ORDER_PRODUCT'
export const UPDATE_ORDER_PRODUCT = 'UPDATE_ORDER_PRODUCT'
export const REMOVE_ORDER_PRODUCT = 'REMOVE_ORDER_PRODUCT'
export const COPY_ORDER_PRODUCT = 'COPY_ORDER_PRODUCT'
export const SUBMIT_ORDER = 'SUBMIT_ORDER'
export const FETCH_ORDER = 'FETCH_ORDER'
export const CLEAR_ORDER = 'CLEAR_ORDER'
export const CALCULATE_ORDER_SQM = 'CALCULATE_ORDER_SQM'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE'
export const FETCH_ORDER_TOTALPRICE_SUCCESS = 'FETCH_ORDER_TOTALPRICE_SUCCESS'
export const FETCH_ORDER_TOTALPRICE_FAILURE = 'FETCH_ORDER_TOTALPRICE_FAILURE'